<html>
<head>
<meta name="Author" content="Fabio Nascimento Brandão">
<title>Obscura - www.hpobscura.cjb.net</title>
<script language="Javascript" src="obscura.js"></script>
<link rel=stylesheet type="text/css" href="obscura.css">
</head>
<!-- ------------------------------------------------------------------------

		Obscura		http://www.hpobscura.cjb.net
		 Página Feita Por Fabio Nascimento Brandão
		    Contatos ICQ UIN 42660795 Jøñ £ðrd®
				Copyright 2000

------------------------------------------------------------------------- -->
<body bgcolor="000000" text="000000">
<table cellpadding=0 cellspacing=0 width="100%">
<tr><td align="center" valign="top">
<table cellpadding=0 cellspacing=0 width="100%">
<tr><td width="20" valign="top" bgcolor="202020"><img src="imagens/besq.gif"></td>
<td align="left" bgcolor="202020">
<table cellpading=1 cellspacing=1 border=0>
<tr><td align="center" width="155"><img src="imagens/logo.gif" width="155" height="87"></td>
<td width="100%" align="center" valign="middle"><img src="imagens/banner.gif" width="468" height="60"></td></tr>
</table>
<script language="javascript">
<!--

hoje=new Date();
dia=hoje.getDate();
mes=hoje.getMonth();
semana=hoje.getDay();
todasemana=new Array('Domingo','Segunda-Feira','Terça-Feira','Quarta-Feira','Quinta-Feira','Sexta-Feira','Sábado');
todomes=new Array('Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro');
semana=todasemana[semana];
mes=todomes[mes];
if(dia<10){dia="0"+dia};
document.write('<font class="data">'+semana+', '+dia+' de '+mes+'</font>');


// -->
</script></td>
<td width="20" valign="top" bgcolor="202020"><img src="imagens/bdir.gif"></td></tr>
</table>
<table width="100%">
<tr><td align="left" valign="top" bgcolor="000000" width="130">
<table cellspacing=3 bordercolor="000000" bgcolor="000000" width="130">
<tr><td align="left" bgcolor="202020" class="menu" onmouseover="mudamenu(this,'000000','gray')" onmouseout="mudamenu(this,'202020','ffffff')" onclick="vaimenu('index.php')"><a href="index.php" onmouseover="window.status='Newsletter'; return true;" class="menu">Newsletter</a></td></tr>
</table>
</td>
<td align="left" valign="top" bgcolor="000000">
<table cellpadding=0 cellspacing=0 bgcolor="000000" width="100%" height="100%">
<tr><td width="20" height="20"><img src="imagens/bcima.gif"></td>
<td width="100%" bgcolor="ffffff">&nbsp;</td>
<td width="20" height="20"><img src="imagens/bcima1.gif"></td></tr>
<tr><td bgcolor="ffffff">&nbsp;</td>
<td align="left" valign="top" bgcolor="ffffff" height="100%">
<font color="000000">
<!-- ---------Começo da Página------------------------- -->