<?

// Nome da database MySql, crie uma database com esse nome no MySql Server
$nomedb="h41370_new";

// Nome da tabela que será salva o guestbook
$nometabela="new";

// Seu email
$emailrem="contatos@hotboys.com.br";

// MySql Server
$mysqlhost="localhost";

// Nome do usuário MySql
$mysqluser="h41370";

// Senha do MySql
$mysqlpass="alan859652";

// Senha para a parte administrativa
$senha="fabio";

?>