<!-- ---------Fim da Página---------------------------- -->
</td>
<td bgcolor="ffffff">&nbsp;</td></tr>
<tr><td width="20" height="20"><img src="imagens/bbaixo.gif"></td>
<td width="100%" bgcolor="ffffff">&nbsp;</td>
<td width="20" height="20"><img src="imagens/bbaixo1.gif"></td></tr>
</table>
</td></tr>
</table>
<table width="100%" bgcolor="000000" cellpadding=0 cellspacing=0 border=0>
<tr><td bgcolor="202020">&nbsp;</td><td align="center" bgcolor="202020"><font class="data">Página feita por <a href="mailto:jon-lord@bol.com.br?subject=Obscura" class="data" onmouseover="window.status='Mande-me um E-Mail'; return true;">Fabio N. B.</a> ICQ:42660795</font></td><td bgcolor="202020">&nbsp;</td></tr>
<tr><td width="20" height="20"><img src="imagens/besq1.gif"></td><td bgcolor="202020">&nbsp;</td><td width="20" height="20"><img src="imagens/bdir1.gif"></td></tr>
</table>
</td></tr>
</table>
</body>
</html>
<script language="NotRecognized">
<!--VirtualAvenueBanner-->
</script>